### ISSUE TITLE
TS lsp doesn't work

### ISSUE THREAD

**Issue by jahn-mtg** [ChristianChiarulli/nvcode#166]
I've got the latest code and have run :LspInstall typescript, says it installed properly. But when I open up a index.js lsp, doesn't work. I have  lsp working on other types  (docker, lua, bash). I even tried it with projects with package.json in the root but still nothing.  What am I missing?

**Comment by ChristianChiarulli** [comment]
hmm, I'll have to investigate

**Comment by ChristianChiarulli** [comment]
Can you give me the output of:

```
:lua print(DATA_PATH)
```

and

show me the config for js-ts-ls.lua under the lsp folder?

**Comment by jahn-mtg** [comment]
:lua print(DATA_PATH) 
`/home/jinahn/.local/share/nvim`

js-ts-ls.lua
`require'lspconfig'.tsserver.setup {
    cmd = {DATA_PATH .. "/lspinstall/typescript/node_modules/.bin/typescript-language-server", "--stdio"},
    on_attach = require'lsp'.tsserver_on_attach,
    -- This makes sure tsserver is not used for formatting (I prefer prettier)
    -- on_attach = require'lsp'.common_on_attach,
    settings = {documentFormatting = false}
}
`
i can confirm i have `/home/jinahn/.local/share/nvim/lspinstall/typescript/node_modules/.bin/typescript-language-server`

**Comment by jahn-mtg** [comment]
Also not sure if I its related, but everytime I save a .js file i  get this error message

Error detected while processing BufWritePre Autocommands for "*.js":
E5108: Error executing lua ...neovim/HEAD-691a72b_2/share/nvim/runtime/lua/vim/lsp.lua:1137: table index is nil

commenting out line 43 in `nv-utils/init.lua` gets rid of the error message but doesn't fix anything.

**Comment by GE47** [comment]
I have the same issues

**Comment by ChristianChiarulli** [comment]
hmm can you post the output of 

```
:LspInfo
```

**Comment by ChristianChiarulli** [comment]
The second error is in regards to formatting which will be handled in the next stream.

**Comment by jahn-mtg** [comment]
`  Configured servers: html, efm, jsonls, yamlls, bashls, cssls, dockerls, vimls, graphql, pyright, tsserver, sumneko_lua 
  Neovim logs at: /home/jinahn/.cache/nvim/lsp.log 
   
  0 client(s) attached to this buffer:  
   
  3 active client(s):  
   
    Client: sumneko_lua (id 1) 
    	root:      /mnt/c/Users/jinahn/Dropbox/Documents/Development/setup/dotenv/dotconfig/nvim 
    	filetypes: lua 
    	cmd:       /home/jinahn/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server -E /home/jinahn/.local/share/nvim/lspinstall/lua/main.lua 
    	 
   
   
    Client: sumneko_lua (id 2) 
    	root:      /mnt/c/Users/jinahn/Dropbox/Documents/Development/setup/dotenv/dotconfig/nvim/lua/lsp 
    	filetypes: lua 
    	cmd:       /home/jinahn/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server -E /home/jinahn/.local/share/nvim/lspinstall/lua/main.lua 
    	 
   
   
    Client: sumneko_lua (id 3) 
    	root:      /mnt/c/Users/jinahn/Dropbox/Documents/Development/setup/dotenv/dotconfig/nvim/lua/nv-utils 
    	filetypes: lua 
    	cmd:       /home/jinahn/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server -E /home/jinahn/.local/share/nvim/lspinstall/lua/main.lua 
    	 
   
   
  Clients that match the filetype markdown: 
     
    Config: efm 
    	cmd:               /home/jinahn/.local/share/nvim/lspinstall/efm/efm-langserver 
    	cmd is executable: False. Please check your path and ensure the server is installed 
    	identified root:   None 
    	custom handlers:    
`

**Comment by Keningar** [comment]
I don't know if it helps you, but in my case i have typescript-language-server installed globaly so i make it work with:
`require'lspconfig'.tsserver.setup {
    cmd = {"typescript-language-server", "--stdio"},
    on_attach = require'lsp'.tsserver_on_attach,
    -- This makes sure tsserver is not used for formatting (I prefer prettier)
    -- on_attach = require'lsp'.common_on_attach,
    settings = {documentFormatting = false}
}`

**Comment by jahn-mtg** [comment]
based on your setup, is your lsp by using npm install typescript-server? Recently @ChristianChiarulli changed the setup to use :LspInstall instead. if you see in my ts lua file there's a `cmd = {DATA_PATH ..` which he setup to be a global variable pointing to the Lspinstall dir

**Comment by ChristianChiarulli** [comment]
I think I fixed this in the livestream

**Comment by GE47** [comment]
It worked for me when I changed the setup back to the npm i -g and made the cmd like the lsp docs say.

**Comment by GE47** [comment]
> I don't know if it helps you, but in my case i have typescript-language-server installed globaly so i make it work with:
> 
> ```
> 
> require'lspconfig'.tsserver.setup {
> 
>     cmd = {"typescript-language-server", "--stdio"},
> 
>     on_attach = require'lsp'.tsserver_on_attach,
> 
>     -- This makes sure tsserver is not used for formatting (I prefer prettier)
> 
>     -- on_attach = require'lsp'.common_on_attach,
> 
>     settings = {documentFormatting = false}
> 
> }
> 
> ```
This worked for me

**Comment by jahn-mtg** [comment]
hm I watched the stream and tried everything you added, I even tried just hardcoding the path to the typescript language, I even tried to use the above suggestions, but still don't have typescript lsp working. All other lsp I've tried work fine. :(

**Comment by GE47** [comment]
> hm I watched the stream and tried everything you added, I even tried just hardcoding the path to the typescript language, I even tried to use the above suggestions, but still don't have typescript lsp working. All other lsp I've tried work fine. :(

Did npm install -g tsserver from the terminal and did the line from the suggestion?

**Comment by jahn-mtg** [comment]
yea tried all that

**Comment by jahn-mtg** [comment]
In my local copy I had javascript snippets plugin installed but I realized @ChristianChiarulli removed those plugins from his.  I uninstalled those plugins plus added his most recent changes and that fixed the issue for me
